In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

print(np.arange(10)) #create numpy array values from 0 to n-1

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
L = range(1000)
%timeit [i**2 for i in L]

281 µs ± 8.65 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.58 µs ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.ndim

1

In [12]:
a.shape

(4,)

In [13]:
len(a)

4

In [14]:
b = np.array([[1,2,3],[4,5,6]]) #2-d array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [17]:
len(b) #return size of first dimension

2

In [18]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]]) #3d-array


3

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [21]:
len(c)

2

In [24]:
b = np.arange(1,10,2) #create numpy array startval = 1; endval < 10; step-size = 2;
b

array([1, 3, 5, 7, 9])

In [23]:
a = np.linspace(0,1,6) #creates number line start=0, end = 1, number of points = 6
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a = np.ones((3,3)) #creates 2d array with all elements being one
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
b = np.zeros((3,3)) #creates 2d array with all elements being zeros
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.eye(3) #create 2d array with diagonal element as one's (Identity matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3,2) #3rows and 2 cols,with diagonal element as one's

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [32]:
a = np.diag([1,2,3]) #create a matrix with diagonal elements equals to the list
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
np.diag(a) #extracts diagonal element from array

array([1, 2, 3])

In [37]:
a = np.random.rand(4) #return 4 random numbers
a

array([0.38945799, 0.9748383 , 0.92859689, 0.56108475])

In [38]:
a = np.arange(10)
a.dtype

dtype('int64')

In [39]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
d = np.array([1+2j,2+4j])
d.dtype

dtype('complex128')

In [42]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [43]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [44]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#slicing
a[1:8:2] #start index = 1,end index = 8, step size = 2

array([1, 3, 5, 7])

In [47]:
a[5:]  = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [48]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [49]:
np.shares_memory(a,b)

False

In [52]:
#creating random numbers in range
a = np.random.randint(1,20,15) #starting from 1 till < 20 and 15 such random numbers
a

array([14,  4, 17, 16, 10, 18,  7, 10,  4, 15, 19, 12,  6, 16, 18])

In [53]:
mask = (a%2 == 0)
even_no = a[mask]
even_no

array([14,  4, 16, 10, 18, 10,  4, 12,  6, 16, 18])

In [54]:
a[mask]=-1
a

array([-1, -1, 17, -1, -1, -1,  7, -1, -1, 15, 19, -1, -1, -1, -1])

In [55]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
a[[7,2]] = 200 #change index 7 and 2 to 200
a

array([  0,  10, 200,  30,  40,  50,  60, 200,  80,  90])

In [58]:
a = np.array([1,2,3,4])
a+1
a**2

array([ 1,  4,  9, 16])

In [61]:
c = np.diag([1,2,3,4])
print(c*c)
print("=============")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [62]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b #element wise comparision

array([False,  True, False,  True])

In [63]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b) #check two arrays are equal or not

False

In [67]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
print(np.logical_or(a,b)) #logical or of a and b
print(np.logical_and(a,b)) #logical and of a and b

[ True  True  True False]
[ True False False False]


In [73]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [74]:
np.log(a)

<ipython-input-74-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [72]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [75]:
a = np.arange(4)
a + np.array([1,2])   #shape mismatch

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [76]:
a = np.array([1,2,3,4])
np.sum(a)

10

In [77]:
x = np.array([[1,1],[2,2]])
x.sum(axis=0) #column first dimension sum

array([3, 3])

In [78]:
x.sum(axis=1) #row first dimension sum

array([2, 4])

In [80]:
x = np.array([1,3,2])
x.min() #minimum element in array
x.max() #maximum element in array

3

In [81]:
x.argmin()  #index of minimum element

0

In [82]:
x.argmax() #index of maximum element

1

In [84]:
np.all([True,True,False])

False

In [85]:
np.any([True,False,True])

True

In [88]:
a = np.zeros((50,50))
np.any(a!=0)
np.all(a == a)

True

In [92]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

In [93]:
x = np.array([1,2,3,1])
x.mean()

1.75

In [94]:
np.median(x)

1.5

In [95]:
y = np.array([[1,2,3],[5,6,1]])
np.median(y,axis=1)

array([2., 5.])

In [96]:
x.std() #calculate standard deviation

0.82915619758885

In [97]:
data = np.loadtxt("untitled.txt")

In [98]:
data

array([[ 1900., 30000.,  4000., 48000.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 35620.],
       [ 1904., 44200., 19000., 15654.],
       [ 1905., 54700.,  8000., 54233.]])

In [100]:
year,hares,lynxes,carrots = data.T #transpose of data
print(year)

[1900. 1901. 1902. 1903. 1904. 1905.]


In [101]:
populations =  data[:,1:] #all rows but columns from 1st skipping 0th column
populations

array([[30000.,  4000., 48000.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 35620.],
       [44200., 19000., 15654.],
       [54700.,  8000., 54233.]])

In [103]:
populations.std(axis=0) #standard deviation column wise

array([15962.2210234 , 10722.93751212, 12558.30577413])

In [106]:
#which species has highest population each year?
print(np.argmax(populations,axis=1)) #index of each rows of max value
print(np.max(populations,axis=1)) #max value of each rows

[2 2 0 0 0 0]
[48000. 48200. 70200. 77400. 44200. 54700.]


In [9]:
#Broadcasting in numpy 
#if we are adding two matrices which is not suitable to add it will replicate the array to make it suitable.
a = np.tile(np.arange(0,40,10),(3,1)) #create 1d array from 0 to 30 (3,1) means replicate 1d array 3 times and whole array 1 time.
print(a)

a=a.T #transpose matrix
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [10]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [11]:
a+b #here broadcasting happenning even though shape of b is not compatible, before adding it gets replicated 4 times.

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [14]:
a = np.arange(0,40,10)
a.shape

(4,)

In [15]:
a = a[:,np.newaxis] #add new axis ->2D array (convert 1D array to 2D array)
a.shape

(4, 1)

In [16]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [17]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [18]:
#Flattening
a = np.array([[1,2,3],[4,5,6]])
a.ravel() #convert 2D array to 1D array

array([1, 2, 3, 4, 5, 6])

In [19]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [20]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [21]:
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b[0,0]=100
a #b and a point at same memory location

array([[100,   2,   3],
       [  4,   5,   6]])

In [24]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0]=50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [26]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [27]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [28]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [29]:
a[0,2,1]

5

In [30]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [32]:
b = a
a.resize((4,)) #if two variable poiting to same array resizing gives error.

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [33]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1) #sort row wise
b

array([[4, 5, 6],
       [2, 2, 3]])

In [34]:
a.sort(axis=1) #in-place sort
a

array([[4, 5, 6],
       [2, 2, 3]])

In [35]:
#sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a) #sort element and show index corresponding to original array
j

array([2, 3, 1, 0])

In [36]:
a[j]

array([1, 2, 3, 4])